### ISSUE TITLE
webgl not supported?

### ISSUE THREAD

**Issue by zhihua-chen** [plotly/angular-plotly.js#1]
Fresh ng cli project. Trying to display a scatter3d chart using this plotly component.

Page in chrome complains "Webgl is not supported by your browser - visit http://get.webgl.org for more info". Now if you click on it, get.webgl.org will tell you that "Your browser supports WebGL".

Some kind of ify-loader issue?

Edit: 

So I ng eject the project, and add ify-loader to webpack.config.js. Now everything works.

Remaining question:

Does this component require ify-loader, and an ng ejected project, for webgl charts?

**Comment by andrefarzat** [comment]
@zhihua-chen could you show the code you used to plot the graph ?

**Comment by nicolaskruchten** [comment]
I had the same issue in jupyterlab-chart-editor and we had it in plotly.py as well :)

https://github.com/plotly/jupyterlab-chart-editor/commit/53d3f270f1bcfe76ae7efce9e80f9b12e2e1cf0a

**Comment by zhihua-chen** [comment]
HTML
`    <plotly-plot [data]="data"></plotly-plot>
`

TS
```
data = [
    { x: [1, 2, 3], y: [2, 6, 3], z: [1, 2, 3], type: 'scatter3d', mode: 'lines+points', marker: {color: 'red'} }
    ];
```

**Comment by zhihua-chen** [comment]
@nicolaskruchten Yes.

Changing the second line in node_modules/angular-plotly.js/esm5/angular-plotly.js.js to `import * as Plotlyjs from 'plotly.js/dist/plotly';` worked.

**Comment by andrefarzat** [comment]
Thank you, @nicolaskruchten 😸 
@zhihua-chen just released the 0.1.10 version with this fix. Please, update it 😺

**Comment by zhihua-chen** [comment]
@nicolaskruchten @andrefarzat Thank you all! Just updated to 0.1.10 and everything is working now.

**Comment by ekmaes** [comment]
Hi, I'm still having the issue of "webgl is not supported by your browser". 
However, it worked a few minutes ago..
Anything you could recommend me to do?

**Comment by andrefarzat** [comment]
@ekmaes this might be an issue with `plotly.js` itself, not this angular wrapper. Or maybe you're using `ng serve --prod` and the final bundle is compromised ?

**Comment by TobiasBreuer** [comment]
I'm recently seeing the same issue in various browsers with plotly.js in Angular (Note: plotly.js! Not using the angular wrapper as of now) but I guess it could well be the same issue.

The issue only shows up in production build (so either running `ng serve --prod` or using the deploy package of `ng build --prod`). 

The issue came up when we updated plotly.js in our angular application.
The last version that works in production mode seems to be plotly.js 1.41.3
Everything later than this version results in the "WebGL not supported" exception - and as this wrapper is already using plotly.js 1.43.1 I could imagine, that this leads to the same result.

**Comment by Issafalcon** [comment]
@TobiasBreuer - Thanks for that comment. I was having the same issue after updating to plotly.js version 1.51.1, to fix an issue with bar charts ignoring the bar width config option (not using Angular, just vanilla js). Suddenly, our 3D scatter plots started showing the message that WebGL is not supported, despite using latest version of Chrome. Dropped back to version 1.41.3, and the 3D charts are now rendering correctly again (and the bar width issue is also fixed). Could have spent a while trying multiple versions if I hadn't stumbled on this!

**Comment by Ashley-Clementi** [comment]
I also found that our 3D scatter plots started showing the message that WebGL is not supported messages after I upgraded plotly.min.js (in both Edge and Chrome). Also confirmed this problem was for releases after plotly 1.41.3.

After some debugging I realised that Plotly would present this message if a plot failed to draw twice.
I then found that MVC ScriptBundle minification of "release" builds was reordering the javascript incorrectly and that cause an exception during drawing the plot, which has nothing to do with WebGL!

My fix is to call ScriptBundle.Transforms.clear() (disable minification of the already minified plotly.min.js).

**Comment by archmoj** [comment]
> I also found that our 3D scatter plots started showing the message that WebGL is not supported messages after I upgraded plotly.min.js (in both Edge and Chrome). Also confirmed this problem was for releases after plotly 1.41.3.

@Ashley-Clementi 
Which version of Chrome and operating system you are using?

**Comment by HDeiro** [comment]
> @andrefarzat I'm 99% sure this is due to this line: https://github.com/plotly/angular-plotly.js/blob/master/src/app/plotly/plotly.service.ts#L2
> 
> If you change it to `import * as Plotlyjs from 'plotly.js/dist/plotly';` then this problem will go away :)

This solved my problem. I was not even using angular-plotly, just plotly itself.

**Comment by ssalveMobiltex** [comment]
Hi, I'm still having the issue of "webgl is not supported by your browser".

Angular Plotly version  -  "angular-plotly.js": "^5.1.0",
    "plotly.js-dist": "^2.24.2",
    "plotly.js-dist-min": "^2.24.2",
