### ISSUE TITLE
(selected) does not work although (selecting) does 

### ISSUE THREAD

**Issue by amellnik** [plotly/angular-plotly.js#21]
I'm not sure why this particular event should act differently from the others, but `(selected)` doesn't seem to work.  

I can't get this package working in stackblitz but a minimal angular-cli project that demonstrates this can be seen [here](https://github.com/amellnik/clarity-plotly-crossfilter/tree/2726e4c17e84b080b5f6bbcc25ab4146d679b28f).  Selecting points on the left plot triggers a bunch of `(selecting)` events but completing the selection does not trigger a `(selected)`.  For some reason single-clicking anywhere on plot generates a `(selected)` event with an undefined payload.

**Comment by amellnik** [comment]
It looks like others have seen this too: https://stackoverflow.com/questions/52643922/some-plotly-chart-events-dont-work-properly-in-angular-6

**Comment by packard15** [comment]
Hello,
I think this problem occur when data array is not empty.
In my case, if my chart is **empty** then the selection's trace is visible and `(selecting)` / `(selected)` events are triggered.
But when data are added, the problem occur.

For my needs, i had to create `MyPlotComponent` inherited `PlotComponent`. 
I noticed that, if i comment `this.updatePlot()` in `ngDoCheck` function, the selection work correctly (selection trace and events). 
To me, it's weird that `updatePlot` is called when the user is selecting elements on the chart.
The reason is that data are changing because makers's opacity is changing (if marker is selected or not)
so in... 
```typescript
ngDoCheck() {  
  let shouldUpdate = false;  
  ...
  if (this.dataDiffer) {  
    const dataHasDiff = this.dataDiffer.diff(this.data);  
    if (dataHasDiff) {  // dataHasDiff is not null or undefined
      shouldUpdate = true;  
    }  
  }
  ...
  if (shouldUpdate && this.plotlyInstance) {  
    this.updatePlot();  //updatePlot is called
  }  
}
```
 And the plot is updated. 
 I disable this call when the user is selecting data to solve this. 
I hope this could help you

**Comment by andrefarzat** [comment]
@packard15 may I ask you the code change you made to solve this ?

**Comment by amellnik** [comment]
@packard15 probably has a better one, but my hacky workaround is to listen to the `(selecting)` events and keep a record of the most recent one in my component, then use that:

```html
<plotly-plot *ngIf="scatter.data" [data]="scatter.data" [layout]="scatter.layout" 
    [config]="{modeBarButtonsToRemove: ['sendDataToCloud']}"
    (selecting)="handleSelecting($event)"></plotly-plot>
```

```typescript
  @Debounce(500)
  handleSelecting(event: any) {
    this.last_selection_data = event;
  }
```

**Comment by packard15** [comment]
Hello,
i can't give you the  code change I made, it was deleted because our needs are changed. We disable ngDoCheck for auto update, and we update the plot when we only need it. I can not find the commits I made to fix it.
Although it's been I remember doing this:

```typescript

export class DwPlotComponent extends PlotComponent {
    private _isSelecting = false;
    ... // all definitions
    
    // Override ngOnInit
	ngOnInit(): void {  
	    super.ngOnInit()
		this.selecting.subscribe(() => { 
			  console.log('is selecting');   
			  this._isSelecting = true;  
		});  

		this.selected.subscribe((data: PlotlyJs.PlotSelectionEvent) => {  
			console.log('selected');  
			this._isSelecting = false;  
	   }
	}
		
	//Override ngDoCheck
	ngDoCheck() {  
	  if(!this._isSelecting) {
			 let shouldUpdate = false;  
			 ...
			 if (this.dataDiffer) {  
			   const dataHasDiff = this.dataDiffer.diff(this.data);  
			   if (dataHasDiff) {  // dataHasDiff is not nullbecause markers / lines / bar ... opacity change when they are selected or not 
			     shouldUpdate = true;  
			   }  
			 }
			 ...
			 if (shouldUpdate && this.plotlyInstance) {  
			   this.updatePlot();  //updatePlot is called
			 }  
		}
	}
}
```
I think it wasn't a bad option to disable this automatic call  this.updatePlot() for my project when we are selecting due to the fact it's would look weird to have a whanging plot during the selection.

**Comment by jorrog** [comment]
(selected) is working in latest version

**Comment by amellnik** [comment]
Confirmed working with `angular-plotly.js@1.0.1` and `plotly.js@1.44.1`, closing.  Thanks!

**Comment by priyavenkat95** [comment]
I am also facing the same issue. I used "angular-plotly.js@1.0.1 and plotly.js@1.44.1". But (selected) not working in Plotly.

I used the code below: 
<plotly-plot *ngIf="donut.data" [data]="donut.data" [layout]="donut.layout"    (selected)="handleSelecting($event)"></plotly-plot>

**Comment by eawachtel** [comment]
i get the $event with my click using  (plotly_click) = "function($event)" , but is the X and Y for the point clicked (for scatter) included in that click event data?  I can't seem to find it anywhere

**Comment by andrefarzat** [comment]
@amellnik @packard15 thanks a lot for clarifying that the issue is related to `updatePlot` being called every time anything changes. This brings different issues in several other different contexts. The simplest (and better maintainable) solution I figured out is to add properties (`updateOnLayoutChange` and `updateOnDataChange`) to give the developer the option to update on these changes or not. When both are false, the `plotly-plot` component is updated only when the developer forces it (calling via `PlotlyService` or incrementing the `revision` property.

Again, thanks a lot guys 😸
