### ISSUE TITLE
Support Angular 8.x

### ISSUE THREAD

**Issue by matthewwiesen** [plotly/angular-plotly.js#69]
It seems that this module does not function correctly when creating a new Angular 8.x app.

Steps to reproduce:

Using @angular/cli@8.1.0

```
$ ng new my-project
$ cd my-project
$ npm install angular-plotly.js plotly.js --save
```

package.json is updated with the following versions:

```
"angular-plotly.js": "^1.3.2",
"plotly.js": "^1.48.3",
```

Add plotly to app.module.ts:

```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import * as PlotlyJS from 'plotly.js/dist/plotly.js';
import { PlotlyModule } from 'angular-plotly.js';

PlotlyModule.plotlyjs = PlotlyJS;

@NgModule({
    imports: [CommonModule, PlotlyModule],
    ...
})
export class AppModule { }
```

At this point, just try to serve up angular's default homepage included with the app will now result in the error with plotly.js attempting to read 'document' which is undefined.

**Comment by andrefarzat** [comment]
Looks like this is a bug with `plotly.js` itself (inside ES6 modules). See: https://github.com/plotly/plotly.js/issues/3518
This might be related to the new compiler (ivy). I will dig on it, but for now, you can use `PlotlyViaCDNModule` to not interrupt your development. See: https://github.com/plotly/angular-plotly.js#plotly-via-cdn-module

**Comment by matthewwiesen** [comment]
This is not related to Angular Ivy. Ivy is curretnly opt-in on Angular 8.

The ng new command will not enable ivy unless you pass --enable-ivy option to ng new. 

I had not tested with Ivy so that could have additional issues.

Regarding use of CDN, this will not work for us since the application is hosted internally without access to the CDN.

https://angular.io/guide/ivy

**Comment by andrefarzat** [comment]
@matthewwiesen I thought Ivy was already a thing because of "Differential Loading by Default". That's the current issue. Once `plotly.js` has the issue with ES6 modules (https://github.com/plotly/plotly.js/issues/3518). I could solve the issue forcing the typescript to be generated as `"target": "es5"` making it **not** use the `<script src="..." type="module" />`, thus both `plotly.js` and angular code is served by "legacy" way. 

Please check this link for more informations:  https://blog.angular.io/version-8-of-angular-smaller-bundles-cli-apis-and-alignment-with-the-ecosystem-af0261112a27

This is a solution regarding that the problem isn't within `angular-plotly.js` itself, but with the dependency

**Comment by matthewwiesen** [comment]
Thanks for the additional clarification here. I'll follow up upstream plotly.js issue to see when this can be resolved.

**Comment by Arjun-Shinojiya** [comment]
Is this plotly.js issue resolved.I am trying to integrate plotly.js but getting same error in angular 8

**Comment by andrefarzat** [comment]
@Arjun-Shinojiya I've seen that you looked up at the plotly/plotly.js#3518 issue 😸
