### ISSUE TITLE
Getting Error 'Uncaught ReferenceError: t is not defined'

### ISSUE THREAD

**Issue by iubhatt17** [plotly/angular-plotly.js#76]
I am using Plotly via Windowmodule currently in my angular 8 proejct. In local I checked the map and it was working fine but in live server , plotly is giving me this error.

**Uncaught ReferenceError: t is not defined** 

I checked in devtool console , the error is in this line 
 **var n = "undefined" != typeof window ? window : void 0 !== t ? t : "undefined" != typeof self ? self : {};**
I dont know how to resolve it.Please help to resolve this issue
![Screenshot from 2019-08-30 12-09-55](https://user-images.githubusercontent.com/34944501/63998662-3aa7a200-cb1f-11e9-82d8-f1dc6ba556b1.png)

**Comment by andrefarzat** [comment]
@iubhatt17 you said that this happens only in production? What command are you using to build/deploy ? `ng build --prod` ? `ng build --prod --aot` ?

**Comment by iubhatt17** [comment]
@andrefarzat I am basically using ng build --prod but in project build also not getting any error.Error which I am getting is after accessing map in live server.

**Comment by andrefarzat** [comment]
I think the issue is related to plotly.js itself and ES6 modules: plotly/plotly.js#3518

As a quick solution, changing in the tsconfig.json the compilerOptions.target property to "es5" might solve the issue. Or using PlotlyViaCDNModule or PlotlyViaWindowModule to avoid the angular transpiler to minify the plotly.js code
