### ISSUE TITLE
Responsive angular-plotly inside mat-tab control

### ISSUE THREAD

**Issue by AnyFlippingUsernameWillDo** [plotly/angular-plotly.js#9]
Hi,

I have a question regarding the use of angular-plotly inside a mat-tab component.

I have a component below which works well to responsively resize when added to another simple page component.

```
<div style="width:100%;height:100%;">
    <plotly-plot [data]="plotlyGraphData" [layout]="plotlyGraphLayout" [useResizeHandler]="true" [config]="plotlyGraphOptions" [style]="{height:'100%', width:'100%'}"></plotly-plot>
</div>
```

However if this component is placed within a mat-tab component then none of the plots are resized correctly upon switching tabs. 
We also often see the message "core.js:1440 ERROR Error: Uncaught (in promise): Error: Resize must be passed a displayed plot div element.
Error: Resize must be passed a displayed plot div element."

We've had similar issues in the past when wrapping plotly in our own angular component and had to workaround this by resizing the grid in ngAfterContentChecked like so

```
ngAfterContentChecked(): void {
    const element = this.plotlyDiv.nativeElement;

    if (this.isVisible === false && element.offsetParent != null) {
      this.isVisible = true;
      // Refresh the grid
      this.resizePlotly();
    } else if (this.isVisible === true && element.offsetParent == null) {
      this.isVisible = false;
    }
  }
```

Is there any chance that this could be looked into please? Or, if not is there any suggestion of how we could handle it effectively.

Thanks.

**Comment by arlowhite** [comment]
I think this is an issue with `MatTab` more than Plotly. The layout may not size things correctly during tab animation.

If you're on Angular 6, try [lazy loading](https://material.angular.io/components/tabs/overview#lazy-loading)
 `<ng-template matTabContent>`
I haven't experimented with it since I'm on Angular 5 at the moment.

Otherwise, I think my trick was to only render the plotly component if the selectedTab was that tab.
`<plotly-plot *ngIf="selectedIndex === X">`
I think the selectedTabIndex changes after tab animation ends, so layout should work correctly at this point.

You may also need to give Plotly a size or if autosize, give the tab container a height.
Also, maybe change [dynamic height](https://material.angular.io/components/tabs/overview#dynamic-height)

Hopefully one of these approaches works for you.

**Comment by AnyFlippingUsernameWillDo** [comment]
Thanks, we've switched to Angular 6 so the lazy loading looks like a good option.
